### ISSUE TITLE
add "confirm password" field in new account registration page register.ejs

### ISSUE THREAD

**Issue by aniketdvd** [aniketdvd/webams#6]
Add confirm pasword field in register.ejs
Make sure the password matches the one in confirm field.

**Comment by jYOtisingh0-o** [comment]
@aniketdvd assign this to me

**Comment by swastikdwivedi** [comment]
@aniketdvd assign to me

**Comment by aniketdvd** [comment]
@jYOtisingh0-o @swastikdwivedi add js validation for password and confirm password field.
